#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`
fraction=1.0 
discharge=5.0
disturbancefraction=0.15
Uh=5.6
waterdepth=`python -c "print($discharge/$Uh)"`
xx=`python -c "print($waterdepth*4*25)"`
disperiod=4
segment=`python -c "print($xx/$disperiod/4)"`

runApplication blockMesh
#runApplication setFields
disU=`python -c "print($Uh*(1-$disturbancefraction))"`
disH=`python -c "print($discharge/$disU)"`
funkySetFields -field alpha.water -expression "$fraction" -time 0 -keepPatches -condition "pos().x<$segment&&pos().y<$disH"
funkySetFields -field U  -expression "vector($disU,0,0)" -time 0 -keepPatches -condition "pos().x<$segment&&pos().y<$disH"


disU=`python -c "print($Uh*(1-$disturbancefraction))"`
disH=`python -c "print($discharge/$disU)"`
funkySetFields -field alpha.water -expression "$fraction" -time 0 -keepPatches -condition "pos().x>($segment*(4*$disperiod-1))&&pos().x<($segment*(4*$disperiod))&&pos().y<$disH"
funkySetFields -field U  -expression "vector($disU,0,0)" -time 0 -keepPatches -condition "pos().x>($segment*(4*$disperiod-1))&&pos().x<($segment*(4*$disperiod))&&pos().y<$disH"

looplimit=`python -c "print($disperiod*2-1)"`
 for num in $(seq 1 $looplimit)
 do
   disU=`python -c "print($Uh*(1-((-1 if $num%2 else 1))*$disturbancefraction))"`
   disH=`python -c "print($discharge/$disU)"`
   funkySetFields -field alpha.water -expression "$fraction" -time 0 -keepPatches -condition "pos().x>($segment*(1+2*($num-1)))&&pos().x<($segment*(1+(2*$num)))&&pos().y<$disH"
   funkySetFields -field U -expression "vector($disU,0,0)" -time 0 -keepPatches -condition "pos().x>($segment*(1+(2*($num-1))))&&pos().x<($segment*(1+(2*$num)))&&pos().y<$disH"
 done

runApplication $application

#------------------------------------------------------------------------------
